name: tutorial
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - matplotlib=3.0.2
  - seaborn=0.11.0
  - scikit-learn=0.19.1
  - keras
 
  - pip
  - pip:
    - mlflow

